# Generated by Django 4.1.7 on 2023-03-09 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('departure', models.CharField(max_length=10)),
                ('picture', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('price', models.IntegerField()),
                ('stars', models.CharField(max_length=2)),
                ('country', models.CharField(max_length=50)),
                ('nights', models.IntegerField()),
                ('date', models.CharField(max_length=50)),
            ],
        ),
    ]
