# Generated by Django 4.1.7 on 2023-03-19 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_city_cards_cit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cards',
            options={'ordering': ['title', 'departure'], 'verbose_name': 'Туры', 'verbose_name_plural': 'Туры'},
        ),
        migrations.RemoveField(
            model_name='cards',
            name='cit',
        ),
        migrations.AlterField(
            model_name='cards',
            name='country',
            field=models.CharField(max_length=50, verbose_name='Страна прибытия'),
        ),
        migrations.AlterField(
            model_name='cards',
            name='date',
            field=models.CharField(max_length=50, verbose_name='Дата отправки'),
        ),
        migrations.AlterField(
            model_name='cards',
            name='departure',
            field=models.CharField(max_length=10, verbose_name='Страна отправки'),
        ),
        migrations.AlterField(
            model_name='cards',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание отеля'),
        ),
        migrations.AlterField(
            model_name='cards',
            name='nights',
            field=models.IntegerField(verbose_name='Количество ночей'),
        ),
        migrations.AlterField(
            model_name='cards',
            name='picture',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='cards',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='cards',
            name='stars',
            field=models.CharField(max_length=2, verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='cards',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название отеля'),
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
