# Generated by Django 4.1.7 on 2023-03-19 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_alter_cards_options_remove_cards_cit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Публикация'),
        ),
    ]
